### ISSUE TITLE
Cannot import SpiceyPy

### ISSUE THREAD

**Issue by InvRules** [ThomasAlbin/Astroniz-YT-Tutorials#45]
Hello - I am struggling trying to import SpiceyPy
I am using Windows 10 laptop.  I was able to run the previous session (setup remote container).

Here is what I am seeing

![image](https://user-images.githubusercontent.com/108376515/176326962-b11058d5-96b8-4392-96f4-fe8b7cf7db29.png)

![image](https://user-images.githubusercontent.com/108376515/176327027-2a6d6813-5044-4391-9f09-effe25afd270.png)

![image](https://user-images.githubusercontent.com/108376515/176327055-40437eea-8ae7-4bf9-844c-43f8a0c1c031.png)

Any help you can provide would be greatly appreciated

Regards

**Comment by InvRules** [comment]
I restarted from the begining in a new folder

Also I went to this site and tried all of the suggestions, but they did not fix the issue.
https://candid.technology/error-loading-preloads-could-not-find-renderer/

One of the suggestions is to run

import plotly.io as pio
pio.renderers.default = 'iframe_connected'

This gave the following error

![image](https://user-images.githubusercontent.com/108376515/176423214-a08b223b-818a-4bb0-9a6c-48c199aa889d.png)

**Comment by InvRules** [comment]
Seems OK now...

**Comment by ThomasAlbin** [comment]
Ehm ... hey there. Thanks for the report. It is weird, since spiceypy is part of the requirements.txt. Thanks for the update!
