### ISSUE TITLE
'Setting an array element with a sequence' error in cell 5 of [ML1]-Asteroid-Spectra/11_dl_autoencoder_reconstruction.ipynb 

### ISSUE THREAD

**Issue by sierrah-hub** [ThomasAlbin/Astroniz-YT-Tutorials#47]
Hi Thomas - I contacted you on twitter about this issue, just putting it down here.
I've also attached the screenshot of the issue that I posted there
![image](https://user-images.githubusercontent.com/76027829/178781897-ea92c808-cb6f-4eca-8bd8-03b998efd854.png)
No worries if this issue is not that important to warrant a fix, I enjoy your tutorials!

**Comment by ThomasAlbin** [comment]
Hey there, thanks for the bug report. I will check it and back to you here in this issue :)
