### ISSUE TITLE
Repository cannot be cloned on Windows

### ISSUE THREAD

**Issue by LosCommodore** [ThomasAlbin/Astroniz-YT-Tutorials#55]
Windows does not accept the following reserved characters:    < : " / \ | ?   on a path. The problem is this file:

 '[Project]-Near-Earth-Objects/results_data/simulation/UNDETECTED_UTC2010-01-01T00:00:00_OppDist15.0_MagDetec22.0_StepSize24.0_HourObs43800.0.parquet'**

Therefore I get an error during cloning:

> git clone --progress --verbose https://github.com/ThomasAlbin/Astroniz-YT-Tutorials.git
> Cloning into 'Astroniz-YT-Tutorials'...
> POST git-upload-pack (174 bytes)
> POST git-upload-pack (262 bytes)
> remote: Enumerating objects: 623, done.
> remote: Counting objects: 100% (623/623), done.
> remote: Compressing objects: 100% (342/342), done.
> remote: Total 623 (delta 274), reused 582 (delta 254), pack-reused 0
> Receiving objects: 100% (623/623), 74.09 MiB | 6.86 MiB/s, done.
> Resolving deltas: 100% (274/274), done.
**> error: invalid path '[Project]-Near-Earth-Objects/results_data/simulation/UNDETECTED_UTC2010-01-01T00:00:00_OppDist15.0_MagDetec22.0_StepSize24.0_HourObs43800.0.parquet'**
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'

Updating git to the newest version and trying out some git-settings (git config --global core.protectNTFS false) didn't help. So as a workaround I forket the repo and deleted the files on github before cloning.

see also: 
https://brendanforster.com/notes/fixing-invalid-git-paths-on-windows/
https://confluence.atlassian.com/bitbucketserverkb/error-invalid-path-during-git-clone-to-windows-client-1085186345.html

proposed solution: abandon windows, buy a mac :) Can you rename the file(s) ?

**Comment by ThomasAlbin** [comment]
Hey there!

Thanks for opening an issue. Unfortunately I cannot test it on a Windows machine. What "path-part" is causing this issue? The brackets? Can you suggest a path-change, for example via a Pull Request?

Best,
Thomas

**Comment by LosCommodore** [comment]
Alright, it was only all about the : character. I fixed in the pull request. 

Thank you, this is a really interesting project! I am looking forward to the xmas holidays when I can really dive into it :)

**Comment by alexjj** [comment]
For others who might be reading this and running Windows, you might want to consider [windows subsystems for linux (WSL)](https://learn.microsoft.com/en-us/windows/wsl/install) as a way to install stuff and get around the Windows issues. VS Code works really nicely with WSL and can make it feel seamless.

**Comment by ThomasAlbin** [comment]
> Alright, it was only all about the : character. I fixed in the pull request.
> 
> Thank you, this is a really interesting project! I am looking forward to the xmas holidays when I can really dive into it :)

Thanks a lot! I will merge the PR with my next upcoming video :)!

> For others who might be reading this and running Windows, you might want to consider [windows subsystems for linux (WSL)](https://learn.microsoft.com/en-us/windows/wsl/install) as a way to install stuff and get around the Windows issues. VS Code works really nicely with WSL and can make it feel seamless.

Indeed alexjj, that is also a very good hint. Thanks!

**Comment by ThomasAlbin** [comment]
The file fix is integrated. I did not merge it with my branch that will be uploaded on Sunday, but merged it now already in the main.

Thanks again!
